# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib graphvec, .registration = TRUE
NULL

#' Record the `list(n, from, to, directed, uid)` a `GraphBackend` was built
#' from in its external pointer's protected slot, which (unlike the Rust
#' graph the pointer addresses) survives `serialize()`/`saveRDS()`, so that
#' `graphvec_backend_revive()` can rebuild the graph after a reload. The
#' uid is also set as a `uid` attribute, which `identical()` compares
#' (unlike the protected slot): every reloaded pointer is null until it's
#' rebuilt, so without it any two reloaded graphs would be `identical()`.
#' @noRd
graphvec_backend_set_source <- function(graph, source) .Call(wrap__graphvec_backend_set_source, graph, source)

#' Rebuild, in place, the Rust graph behind a `GraphBackend` external
#' pointer that came back null from `unserialize()`/`readRDS()` (or a
#' callr/future worker), from the source `graphvec_backend_set_source()`
#' recorded, keeping its uid. In place, so every R object sharing the
#' pointer sees the rebuilt graph. A live pointer, or one without a
#' recorded source, is left as it is.
#'
#' The rebuilt graph is an ordinary extendr `GraphBackend` external
#' pointer of its own, whose address `graph` borrows; it's kept alive (and
#' is eventually freed, by its own finalizer) through `graph`'s protected
#' slot, so `graph` itself needs no finalizer and nothing here depends on
#' how extendr lays out the memory behind the address.
#' @noRd
graphvec_backend_revive <- function(graph) .Call(wrap__graphvec_backend_revive, graph)

#' The shared topology backing a `node_vec`/`edge_vec` pair (non-hyperedge
#' case only -- see `_dev/RUST_BACKEND.md`). Wraps one of several physical
#' `Repr` variants, auto-selected at construction from graph shape
#' (`_dev/petgraph_data_types.md` S3/S5); `directed` is metadata every
#' variant's query methods interpret, not itself part of the shape
#' decision. This keeps the object immutable and shareable: a `node_vec`,
#' its `edges()` reorientation, and any `edge_vec` sliced from it can all
#' hold the same pointer.
#'
#' @export
#'
#' @section Methods:
#'\subsection{Method `new`}{
#'Build a graph on `n` nodes from 1-based `from`/`to` positions.
#'Automatically picks the cheapest `Repr` the graph's shape qualifies
#'for (`_dev/petgraph_data_types.md` S3/S5 -- this decision belongs
#'here, not in R, so there is exactly one place shape detection can
#'drift out of sync with the representation it feeds). Edges are added
#'in input order and never removed afterwards, so edge ids (0-based
#'internally, 1-based at the R boundary) stay stable and match the row
#'order of the R-side edge attribute table, for every representation.
#'
#'Errors (an R error, not a crash) unless every `from`/`to` position is
#'in `1..=n` and the two have the same length: an `NA` arrives as
#'`i32::MIN`, and a position outside the graph would otherwise index
#'out of bounds or, at 0 or below, wrap to a huge `usize` allocation.
#'The R constructors check this first, with friendlier messages.
#'}
#'
#'\subsection{Method `uid`}{
#'A number unique to this graph among every graph built in the R
#'session, never reused (unlike a memory address, which can be once a
#'graph is garbage collected), and starting from a random point per
#'session so it doesn't collide with a graph saved from another one.
#'This is a graph's identity: two R objects are of the same graph
#'exactly when their `GraphBackend`s have the same `uid()`, including
#'after a `saveRDS()`/`readRDS()` round trip, which rebuilds the graph
#'behind a new address but keeps its uid (`graphvec_backend_revive()`).
#'A double, so it fits an R numeric exactly (it's kept to 53 bits).
#'}
#'
#'\subsection{Method `repr_name`}{
#'Which physical representation this backend picked, as a stable name
#'(`"general"`, `"dense"`, `"csr"`) -- the one diagnostic entry point
#'for "which `Repr` is this", replacing what used to be a separate
#'`is_tree()`/`is_dense()`/`is_csr()` boolean per variant. That pattern
#'grew one new `#[extendr]` method -- permanent, exported R API the
#'moment it's added, per this file's own "the method set is the
#'contract" principle -- for every future `Repr` addition; this single
#'method's match arm count grows with `Repr` instead, so the R-visible
#'surface stays fixed no matter how many representations `GraphBackend`
#'eventually holds.
#'}
#'
#'\subsection{Method `degrees`}{
#'Every node's degree, in node order -- `degree()` (below) for each
#'node in one call, so `node_degree()` and the node predicates cross
#'the R/Rust boundary once rather than once per node. Same `mode` and
#'self-loop semantics as `degree()`, which it is defined by.
#'}
#'
#'\subsection{Method `neighbors_many`}{
#'The neighbours of every node in `nodes` (1-based, repeats allowed),
#'each in increasing order, as one CSR pair `list(ptr, idx)`: node
#'`nodes[k]`'s neighbours are `idx[(ptr[k] + 1):ptr[k + 1]]`, with
#'`ptr` 0-based offsets of length `length(nodes) + 1`. One call for
#'any number of query nodes (`node_neighbors()` splits it into its
#'list result), with the same `mode`, self-loop and one-entry-per-edge
#'semantics as `neighbors()`. Sorted here because `neighbors()`'s own
#'order depends on which `Repr` the graph picked.
#'}
#'
#'\subsection{Method `incident_many`}{
#'The ids of the edges incident to every node in `nodes` (1-based,
#'repeats allowed), each in increasing order, as the same CSR pair
#'`list(ptr, idx)` `neighbors_many()` returns, with 1-based edge ids in
#'`idx`. Same `mode` and self-loop semantics as `neighbors()`: an
#'undirected self-loop is listed once, a directed one twice under
#'`"all"`, so node `nodes[k]` has `degree()` incident edges. Answered
#'from the edge-id incidence index (built on first use), O(degree) per
#'node rather than a scan of every edge.
#'}
#'
#'\subsection{Method `has_edge`}{
#'Adjacency test. For an undirected graph, checks both orientations.
#'}
#'
#'\subsection{Method `edge_endpoints`}{
#'Edges as 1-based `(from, to)` pairs: all of them in
#'construction/edge-id order when `ids` is `NULL`, otherwise those of
#'the 1-based edge ids `ids`, in `ids`' order (repeats allowed). An
#'`NA` id is a missing edge, with `NA` endpoints. Backs `edge_vec`'s
#'`format()`/`$from`/`$to` and `as.igraph()` -- no R-side edge table
#'is needed for topology once this exists -- and lets a slice of a
#'big graph read only its own edges' endpoints, O(length(ids)).
#'}
#'
#'\subsection{Method `induced_subgraph`}{
#'Induced-subgraph remap for a node set sliced/replicated according to
#'`idx`: `idx[j]` is the 1-based *old* node position that *new* node
#'`j` came from, `0` meaning "no source" (a new node with nothing
#'mapping to it -- R's `NA_integer_` maps to this sentinel before the
#'call, since it doesn't survive the R -> Rust integer conversion).
#'Duplicate entries mean a replicated node. An edge is dropped if
#'either endpoint has no surviving new position; an edge whose
#'endpoint(s) were replicated is cloned once per combination.
#'
#'Returns `list(from, to, source_edge)`, all 1-based and in a stable
#'order (new `to` slowest, new `from` fastest, matching
#'`expand.grid(from, to)`'s order): `source_edge[k]` is the original
#'edge id that surviving new edge `k` was cloned from, so the R side
#'can carry edge attribute columns across replication with
#'`edges[source_edge, ]`.
#'
#'This is representation-independent: it works from `edge_list()`'s
#'output alone (S4's edge-identity contract, already upheld there),
#'never `self.repr` directly, so it needs no per-variant duplicate.
#'The result is a plain from/to/source_edge list either way -- it does
#'not construct a new `GraphBackend` itself (R reconstructs one from
#'these lists via `new()`, confirmed by grepping `R/node_vec.R`'s
#'`[.node_vec`), so the *new* backend's shape (which needn't match
#'the old one -- both terms of the density ratio move here, `N`
#'becoming `idx.len()` and `M` however many edges survived or were
#'cloned, so e.g. dropping the centre of a `Repr::Dense` star strips
#'every edge at once and leaves something far below
#'`DENSE_THRESHOLD`, while dropping the isolated nodes that were
#'holding a `Repr::Csr` graph under that threshold pushes what's left
#'above it) is re-decided by `new()`'s own detection from scratch,
#'same as it would be for any other from/to/directed input.
#'}
#'
GraphBackend <- new.env(parent = emptyenv())

GraphBackend$new <- function(n, from, to, directed) .Call(wrap__GraphBackend__new, n, from, to, directed)

GraphBackend$n_nodes <- function() .Call(wrap__GraphBackend__n_nodes, self)

GraphBackend$n_edges <- function() .Call(wrap__GraphBackend__n_edges, self)

GraphBackend$is_directed <- function() .Call(wrap__GraphBackend__is_directed, self)

GraphBackend$uid <- function() .Call(wrap__GraphBackend__uid, self)

GraphBackend$repr_name <- function() .Call(wrap__GraphBackend__repr_name, self)

GraphBackend$degrees <- function(mode) .Call(wrap__GraphBackend__degrees, self, mode)

GraphBackend$neighbors_many <- function(nodes, mode) .Call(wrap__GraphBackend__neighbors_many, self, nodes, mode)

GraphBackend$incident_many <- function(nodes, mode) .Call(wrap__GraphBackend__incident_many, self, nodes, mode)

GraphBackend$has_edge <- function(from, to) .Call(wrap__GraphBackend__has_edge, self, from, to)

GraphBackend$edge_endpoints <- function(ids = NULL) .Call(wrap__GraphBackend__edge_endpoints, self, ids)

GraphBackend$induced_subgraph <- function(idx) .Call(wrap__GraphBackend__induced_subgraph, self, idx)

#' @rdname GraphBackend
#' @usage NULL
#' @export
`$.GraphBackend` <- function (self, name) { func <- GraphBackend[[name]]; environment(func) <- environment(); func }

#' @export
`[[.GraphBackend` <- `$.GraphBackend`

# nolint end
