# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib graphvec, .registration = TRUE
NULL

#' The shared topology backing a `node_vec`/`edge_vec` pair (non-hyperedge
#' case only -- see `_dev/RUST_BACKEND.md`). Edges are stored as a plain
#' directed arc list regardless of `directed`; `directed` is metadata that
#' the query methods interpret, not a different graph type. This keeps the
#' object immutable and shareable: a `node_vec`, its `edges()` reorientation,
#' and any `edge_vec` sliced from it can all hold the same pointer.
#'
#' @export
#'
#' @section Methods:
#'\subsection{Method `new`}{
#'Build a graph on `n` nodes from 1-based `from`/`to` positions.
#'Edges are added in input order and never removed afterwards, so
#'edge ids (0-based internally, 1-based at the R boundary) stay stable
#'and match the row order of the R-side edge attribute table.
#'}
#'
#'\subsection{Method `neighbors`}{
#'1-based neighbour positions of `node` (1-based). For an undirected
#'graph `mode` is ignored and the symmetric neighbour set is always
#'returned (a self-loop appears twice, once via each of the node's
#'outgoing/incoming adjacency lists -- see the crate's tests). For a
#'directed graph, `mode` is `"out"`, `"in"`, or `"all"` (both,
#'concatenated). One entry per incident edge, not deduplicated, so
#'`degree()` can just be `neighbors().len()`.
#'}
#'
#'\subsection{Method `has_edge`}{
#'Adjacency test. For an undirected graph, checks both orientations.
#'}
#'
#'\subsection{Method `edge_endpoints`}{
#'All edges as 1-based `(from, to)` pairs, in construction/edge-id
#'order. Backs `edge_vec`'s `format()`/`$from`/`$to` and `as.igraph()`
#'-- no R-side edge table is needed for topology once this exists.
#'}
#'
#'\subsection{Method `induced_subgraph`}{
#'Induced-subgraph remap for a node set sliced/replicated according to
#'`idx`: `idx[j]` is the 1-based *old* node position that *new* node
#'`j` came from, `0` meaning "no source" (a new node with nothing
#'mapping to it -- R's `NA_integer_` maps to this sentinel before the
#'call, since it doesn't survive the R -> Rust integer conversion).
#'Duplicate entries mean a replicated node. An edge is dropped if
#'either endpoint has no surviving new position; an edge whose
#'endpoint(s) were replicated is cloned once per combination.
#'
#'Returns `list(from, to, source_edge)`, all 1-based and in a stable
#'order (new `to` slowest, new `from` fastest, matching
#'`expand.grid(from, to)`'s order): `source_edge[k]` is the original
#'edge id that surviving new edge `k` was cloned from, so the R side
#'can carry edge attribute columns across replication with
#'`edges[source_edge, ]`.
#'}
#'
GraphBackend <- new.env(parent = emptyenv())

GraphBackend$new <- function(n, from, to, directed) .Call(wrap__GraphBackend__new, n, from, to, directed)

GraphBackend$n_nodes <- function() .Call(wrap__GraphBackend__n_nodes, self)

GraphBackend$n_edges <- function() .Call(wrap__GraphBackend__n_edges, self)

GraphBackend$is_directed <- function() .Call(wrap__GraphBackend__is_directed, self)

GraphBackend$neighbors <- function(node, mode) .Call(wrap__GraphBackend__neighbors, self, node, mode)

GraphBackend$degree <- function(node, mode) .Call(wrap__GraphBackend__degree, self, node, mode)

GraphBackend$has_edge <- function(from, to) .Call(wrap__GraphBackend__has_edge, self, from, to)

GraphBackend$edge_endpoints <- function() .Call(wrap__GraphBackend__edge_endpoints, self)

GraphBackend$induced_subgraph <- function(idx) .Call(wrap__GraphBackend__induced_subgraph, self, idx)

#' @rdname GraphBackend
#' @usage NULL
#' @export
`$.GraphBackend` <- function (self, name) { func <- GraphBackend[[name]]; environment(func) <- environment(); func }

#' @export
`[[.GraphBackend` <- `$.GraphBackend`

# nolint end
